name: Spring Tips Google Sheet Feed Processor

env:
  CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON  }}
  PICKLED_TOKEN: ${{ secrets.PICKLED_TOKEN  }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '55 3 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Run
        run: ./run.sh


