# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

env:
  CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON  }}
  PICKLED_TOKEN: ${{ secrets.PICKLED_TOKEN  }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '55 3 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Run the Google Sheets Processor
        run: |
          pipenv install
          echo "hello "  |  base64
          echo $TICKLED_TOKEN | base64 -d > token.pickle
          echo $CREDENTIALS_JSON | base64 -d > credentials.json
          ls -la
          du -hs token.pickle
          du -hs credentials.json

          pipenv run python sheets.py

#       run: |
#         python -m pip install --upgrade pip
#         pip install flake8 pytest
#         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#     - name: Lint with flake8
#       run: |
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#     - name: Test with pytest
#       run: |
#         pytest
